Ejercicios de la Clase 27
ccollado0307/EjModulo3 pull request #10
Opened 2020-08-17 23:48 UTC by ccollado0307

2020-08-19 23:44 UTC, juanii000 commented
Ceci muy bien el codigo se nota que estas practicando un monton ! Lo unico para remarcar es que a los seter normalmente se los crea para mandarles algo por parametro en vez de hacer que le ponga algo por defecto, despues seguramente haya mas cosas para afinar pero nada grave, estuvieron bien usadas las interfaces y la abstraccion.

2020-08-21 14:55 UTC, juanii000 requested changes
Mirar comentario que deje el otro dia

2020-08-21 21:30 UTC, ccollado0307 commented
Entiendo lo de los set! Me enfoque mas en interface y abstracción!. 
Gracias!

2020-08-24 22:45 UTC, juanii000 approved these changes

2020-08-25 22:44 UTC, merged